[project]
name = "Acoustic-Modeling"
version = "0.1.1"
authors = [
  { name="Oscar Lin", email="olin2702@floridapoly.edu" },
  { name="Carmen Mann", email="cmann4894@floridapoly.edu" },
  { name="Gerardo Claudio", email="EMAIL HERE" },
]
description = "Visualize waveform of audio file, and compute the RT60 of the audio file."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/ExcuseMeee/python-final"